# Generated by Django 2.0.13 on 2019-07-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.Question'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='department',
            field=models.CharField(max_length=20),
        ),
    ]
